twido/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views


# to render full template path
def t(template):
    return 'twido/' + template

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # (r'^robots\.txt$', 'django.views.generic.simple.direct_to_template', {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    # (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

    url(r'^login/$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^register/$', views.RegisterView.as_view(template_name='registration/register.html'), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(template_name='registration/profile.html'), name='profile'),

    url(r'^$', views.IndexView.as_view(template_name=t('index.html')), name='index'),
    url(r'^home/$', views.HomeView.as_view(template_name=t('home.html')), name='home'),
    url(r'^setting/$', views.SettingView.as_view(template_name=t('setting.html')), name='setting'),

    url(r'^social/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>link)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>update)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>login)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),

    url(r'^list/$', views.ListView.as_view(template_name=t('list.html')), name='list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.ListView.as_view(template_name=t('list.html')), name='list'),

    url(r'^task/(?P<pk>[0-9]+)/$', views.TaskView.as_view(template_name=t('task.html')), name='task'),

    url(r'^json/usernames/$', views.ProfileUsernamesJsonView.as_view()),

    # url(r'^', include('user.urls')),

]

# debug & test
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.extend([
        url(r'^test/$', views.test, name='test'),
        url(r'^test/(?P<pk>[0-9]+)/$', views.test, name='test'),
        url(r'^debug/', include(debug_toolbar.urls)),
    ])

twido/models/task.py
#!/usr/bin/env python
# coding: utf-8

"""
Task and list related models
"""
from datetime import timedelta
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.core.validators import validate_comma_separated_integer_list
from django.utils.functional import SimpleLazyObject
from django.utils.translation import ugettext_lazy as _, pgettext_lazy, ugettext_noop
from django.db import transaction
from .common import ProfileBasedModel, UserProfile
from .consts import TaskStatus, Visibility
from pyutils.langutil import PropertyDict
from .social import SocialAccount
from .spider import RawStatus

import simplejson as json
import logging
from twido.parser import Timex3Parser

log = logging.getLogger(__name__)


class List(ProfileBasedModel):
    """
     A list contains one or more things you want or want to do. (todolist, wishlist, ...)
    """
    name = models.CharField(max_length=100)
    reminder = models.DateTimeField(null=True, blank=True)
    visibility = models.IntegerField(choices=Visibility.Choices, default=Visibility.PUBLIC, db_index=True)
    related_users = models.TextField(validators=[validate_comma_separated_integer_list], null=True, blank=True,
                                     db_index=True, verbose_name='Related Persons (comma separated)')
    text = models.TextField(null=True, blank=True)

    # class Meta:
    #     unique_together = ('profile', 'name')

    __default_name = '__default__'

    def __str__(self):
        return "%s (id=%d)" % (self.name, self.id)

    @classmethod
    def get_default(cls, profile):
        try:
            default_list = cls.objects.get(name=cls.__default_name, profile=profile)
        except cls.DoesNotExist:
            default_list = cls(name=cls.__default_name, profile=profile)
            default_list.text = ugettext_noop('The default list contains unlisted tasks.')
            default_list.save(is_default=True)
        return default_list

    @property
    def is_default(self):
        return self.name == self.__default_name

    @property
    def is_sys(self):
        return self.name.startswith('__')

    @property
    def default(self):
        return self.get_default(self.profile)

    def get_name(self):

        if self.is_default:
            return pgettext_lazy('sys list', 'default')
        elif self.is_sys:
            return pgettext_lazy('sys list', self.name.lstrip('_'))
        else:
            return self.name

    def get_related_profiles(self):
        return UserProfile.objects.filter(username__in=(self.related_users.split(',') or ''))

    def get_related_usernames(self):
        return self.related_users.split(',')

    def get_visibility_text(self):
        return Visibility.get_text(self.visibility)

    def get_visibility_icon(self):
        return Visibility.get_icon(self.visibility)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, is_default=False):
        if not is_default and self.name.lower() == self.__default_name:
            raise AttributeError('List name can not be "%s" (reversed default name). ' % self.name)
        return super(List, self).save(force_insert=force_insert, force_update=force_update,
                                      using=using, update_fields=update_fields)

    def delete(self, using=None, keep_parents=False):
        s = str(self)
        log.debug('deleting list %s' % s)
        with transaction.atomic():
            # This query ref to Task. So to avoid recursive reference, need to put List in same file with Task
            Task.objects.filter(list=self, profile=self.profile).update(list=self.get_default(self.profile))
            log.debug('all tasks in todo list %s are moved to default list.' % s)
            super(List, self).delete(using=using, keep_parents=keep_parents)
            log.info('todo list %s is deleted.' % s)


class Task(ProfileBasedModel):
    """
    Base task model for todo, wish and schedule appointment
    """
    created_at = models.DateTimeField(editable=False)
    title = models.CharField(max_length=100)
    status = models.IntegerField(choices=TaskStatus.Choices, default=TaskStatus.NEW, db_index=True)
    visibility = models.IntegerField(choices=Visibility.Choices, default=Visibility.PUBLIC, db_index=True)
    text = models.TextField(null=True, blank=True)
    labels = models.TextField(null=True, blank=True)
    due = models.DateTimeField(null=True, blank=True, db_index=True)
    list = models.ForeignKey(to=List)
    social_account = models.ForeignKey(to=SocialAccount, db_index=True, null=True, blank=True)

    content = models.TextField(null=True, blank=True)
    raw = models.OneToOneField(to=RawStatus, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super(Task, self).save(*args, **kwargs)

    def get_owner_name(self):
        if self.profile and not self.profile.is_sys:
            return self.profile.get_name()
        elif self.social_account:
            return self.social_account.name or self.social_account.account

    def get_at_name(self):

        if self.profile.is_faked:
            uname = self.social_account.account
        else:
            uname = self.profile.username
        return '@' + uname

    def get_status_text(self):
        return TaskStatus.get_text(self.status)

    def get_status_icon(self):
        return TaskStatus.get_icon(self.status)

    def get_visibility_text(self):
        return Visibility.get_text(self.visibility)

    def get_visibility_icon(self):
        return Visibility.get_icon(self.visibility)

    def get_view_path(self):
        return reverse('task', args=(self.id, ))

    def __str__(self):
        return '%s (id=%d)' % (self.title, self.id)


class TaskMeta(models.Model):
    task = models.OneToOneField(to=Task, related_name='meta')
    timex = models.TextField(null=True, blank=True)
    dates = models.TextField(null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    persons = models.TextField(null=True, blank=True)
    simple_text = models.TextField(null=True, blank=True)

    _tags = []
    _dates = []

    def highlight_timex(self):
        return Timex3Parser.highlight(self.timex)

    def get_dates(self):
        if not self._dates:
            self._dates = json.loads(self.dates)
        return self._dates

    def get_tags(self):
        if not self._tags:
            self._tags = json.loads(self.tags)
        return self._tags

    def save(self, *args, **kwargs):
        super(TaskMeta, self).save(*args, **kwargs)
        self._tags = []
        self._dates = []


class SysList(object):
    """
    System pre-defined query list
    """

    soon_days = 3

    def __init__(self, profile, list_model=List, task_model=Task, entries_per_page=10):
        self.ListModel = list_model
        self.TaskModel = task_model
        self.profile = profile
        self.entries = entries_per_page
        self._meta = PropertyDict((
            ('__today', PropertyDict(
                name='__today',
                title=pgettext_lazy('sys list', 'today'),   # for i18n text generation usage
                text=ugettext_noop('Tasks need to be done by today. (including expired)'),
                tasks=SimpleLazyObject(self.__get_today_tasks)
            )),
            ('__coming', PropertyDict(
                name='__coming',
                title=pgettext_lazy('sys list', 'coming'),    # for i18n text generation usage
                text=ugettext_noop('Tasks in near future'),
                tasks=SimpleLazyObject(self.__get_coming_tasks)
            )),
            ('__expired', PropertyDict(
                name='__expired',
                title=pgettext_lazy('sys list', 'expired'),   # for i18n text generation usage
                text=ugettext_noop('Tasks passed the deadline.'),
                tasks=SimpleLazyObject(self.__get_expired_tasks)
            )),
            ('__all', PropertyDict(
                name='__all',
                title=pgettext_lazy('sys list', 'all'),   # for i18n text generation usage
                text=ugettext_noop('All my tasks.'),
                tasks=SimpleLazyObject(self.__get_all_tasks)
            )),
        ))

        # for translation usage (not working)
        # for meta in self._meta.values():
        #     meta.title = pgettext_lazy('sys list', meta.name.lstrip('_'))

        self._lists = PropertyDict()

    @property
    def all(self):
        if not self._lists:
            for name in self._meta.keys():
                self.get(name)
        return self._lists

    def __getitem__(self, item):
        return self.get(item)

    def get(self, name):
        if name not in self._lists:
            meta = self._meta[name]
            lst, created = self.ListModel.objects.get_or_create(profile=self.profile, name=name)
            if created:
                lst.text = meta.text
                lst.visibility = False
                lst.save()
                log.debug('list "%s" created.' % lst)
            lst.tasks = meta.tasks
            self._lists[name] = lst
        return self._lists[name]

    def __get_today_tasks(self):
        now = timezone.now()
        today = timezone.datetime(now.year, now.month, now.day, tzinfo=timezone.utc)
        tomorrow = today + timedelta(days=1)
        return self.TaskModel.objects.filter(profile=self.profile, due__range=(today, tomorrow))

    def __get_coming_tasks(self):
        now = timezone.now()
        soon = now + timedelta(days=self.soon_days)
        return self.TaskModel.objects.filter(profile=self.profile).filter(
            Q(due__gt=now) & Q(due__lt=soon) | Q(due=None))

    def __get_expired_tasks(self):
        return self.TaskModel.objects.filter(profile=self.profile, due__lt=timezone.now()).exclude(

twido/views.py
#!/usr/bin/env python
# coding: utf-8

"""
views
"""

from django.conf import settings
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseBadRequest
from django.urls import reverse

import logging
log = logging.getLogger(__name__)


# to render full template path
def t(template):
    return 'twido/' + template


# test view for some test purpose
if __debug__ and settings.DEBUG:
    def test(request):
        return render(request, t('test.html'))


@require_http_methods(['GET', ])
def index(request):
    context = {}
    if request.user.is_authenticated:
        context['user'] = 'authoried'
    elif request.user.is_staff:
        context['user'] = 'staff'
    else:
        context['user'] = 'forbiden'
    # context = {
    #     # "setting_keys": models.SETTING_NAMES,
    # }
    return render(request, t('index.html'), context=context)

twido/views/account.py
#!/usr/bin/env python
# coding: utf-8
from django.contrib.auth import login
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.http import require_http_methods
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.views import login as login_func_view

from .base import BaseViewMixin
from ..models import UserProfileCreationForm
from ..models import SocialPlatform

import logging
log = logging.getLogger(__name__)


class I18N_MSGS(object):
    reg_success = _('Registration succeed.')
    redirect_to_profile = _('Redirect to profile updating page ... <br>'
                            'If redirection did not start, please <a href="%s">click me to profile</a>.')


@method_decorator(require_http_methods(['POST', 'GET']), name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
@method_decorator(never_cache, name='dispatch')
@method_decorator(sensitive_post_parameters(), name='dispatch')
class RegisterView(TemplateView, BaseViewMixin):
    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        success = False
        profile = None
        request = self.request

        if request.method == "POST":
            form = UserProfileCreationForm(data=self.request.POST)
            if form.is_valid():
                profile = form.save()
                success = True
            else:
                if 'username' in form.errors:
                    del form.errors['username']
        else:
            form = UserProfileCreationForm()

        context['form'] = form
        context['success'] = success

        if success and profile and profile.user and profile.user.is_active:
            login(request, profile.user)
            self.success(I18N_MSGS.reg_success)
            self.success(I18N_MSGS.redirect_to_profile % reverse('profile'))

        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


@method_decorator(require_http_methods(['POST', 'GET']), name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
@method_decorator(never_cache, name='dispatch')
@method_decorator(sensitive_post_parameters(), name='dispatch')
class LoginView(TemplateView, BaseViewMixin):

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        if 'social_platforms' not in context:
            context['social_platforms'] = SocialPlatform
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return self.login(request, template_name=self.template_name, extra_context=context, **kwargs)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        return self.login(request, template_name=self.template_name, extra_context=context, **kwargs)

    def login(self, request, template_name='registration/login.html',
              # redirect_field_name=REDIRECT_FIELD_NAME,
              # authentication_form=AuthenticationForm,
              extra_context=None, redirect_authenticated_user=False):
        return login_func_view(request, template_name=template_name,
                               # redirect_field_name=redirect_field_name,
                               # authentication_form=authentication_form,
                               extra_context=extra_context,
                               redirect_authenticated_user=redirect_authenticated_user)

twido/templates/includes/blank-div-row.html
    <div class="container-fluid">
        <div>&nbsp;</div>
        <div>&nbsp;</div>
        <div class="hidden-sm hidden-xs">&nbsp;</div>
    </div>

twido/templates/includes/django-messags-inc.html
{# Bootstrap 3 message tips by Using Django message middleware #}

<!-- BEGIN message & error -->
        <div id="id_messages">
        </div>

<script language="Javascript">

    var _MSG_LEVELS = {
        debug: {{ DEFAULT_MESSAGE_LEVELS.DEBUG }},
        info: {{ DEFAULT_MESSAGE_LEVELS.INFO }},
        warn: {{ DEFAULT_MESSAGE_LEVELS.WARNING }},
        warning: {{ DEFAULT_MESSAGE_LEVELS.WARNING }},
        error: {{ DEFAULT_MESSAGE_LEVELS.ERROR }},
        success: {{ DEFAULT_MESSAGE_LEVELS.SUCCESS }}
    };

    {# bootstrap classes. change it if use another framework #}
    var _MSG_CLASS = {
        debug: "alert-info",
        info: "alert-info",
        warn: "alert-warning",
        warning: "alert-warning",
        error: "alert-danger",
        success: "alert-success"
    };

    var _MSG_DIV_TEMPLATE = '<div id="{0}" class="alert alert-dismissible {1}">\
        <button type="button" class="close" data-dismiss="alert">×</button>\
        <strong>{2}</strong>\
        <div>\
        {3}\
        </div>\
    </div>';

{#  // KEEP: add .format to String if required (put it to your main .js) #}
{#    String.prototype.format = String.prototype.f = function () {#}
{#        var s = this,#}
{#                i = arguments.length;#}
{##}
{#        while (i--) {#}
{#            s = s.replace(new RegExp('\\{' + i + '\\}', 'gm'), arguments[i]);#}
{#        }#}
{#        return s;#}
{#    };#}

    function _msg(msg, level, title, clear) {
        var box = $("#id_messages");
        var div_id = "id_messages_" + level;
        var div = $("#" + div_id);

        if (level=="error" && !title) title = "Oops!";
        if (title == undefined || title == null) title = "";

        if (!div.length) {
            box.append(_MSG_DIV_TEMPLATE.f(div_id, _MSG_CLASS[level], title, msg+"<br>"));
        } else {
            if (clear) {div.find("div").html('');}
            div.find("div").append(msg+"<br>");
        }
    }

    function _info(msg, clear) { _msg(msg, 'info', '', clear); }
    function _warn(msg, clear) { _msg(msg, 'warn', '', clear); }
    function _error(msg, clear) { _msg(msg, 'error', '', clear); }
    function _success(msg, clear) { _msg(msg, 'success', '', clear); }

    {% for msg in messages %} _msg('{{ msg|safe }}', "{{ msg.level_tag }}");
    {% endfor %}
    {% if form.errors %}
        {% for error in form.non_field_errors %} _error('{{ error|force_escape }}');
        {% endfor %}
        {% for field in form %}{% for error in field.errors %} _error('{{ error|force_escape }}');
        {% endfor %}{% endfor %}
    {% endif %}

</script>
<!-- END message & error -->

twido/templates/includes/editable-head-ref.html
    {% load staticfiles %}
    <link href="{% static 'bootstrap3-editable/css/bootstrap-editable.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap3-editable/js/bootstrap-editable.js' %}"></script>
    <link href="{% static 'twido/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'twido/js/bootstrap-datetimepicker.min.js' %}"></script>
{#    <link href="{% static 'twido/css/select2.min.css' %}" rel="stylesheet" type="text/css">#}
{#    <script src="{% static 'twido/js/select2.full.min.js' %}"></script>#}
    <link href="{% static 'select2-3.4.4/select2.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'select2-3.4.4/select2.js' %}"></script>
    <link href="{% static 'twido/css/select2-bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <script language="JavaScript" src="{% static 'twido/js/bootstrap-confirmation.min.js' %}"></script>
    <script language="JavaScript" type="text/javascript">
        $.fn.editable.defaults.mode = 'inline';
        $.fn.editable.defaults.showbuttons = false;
        $.fn.editable.defaults.onblur = 'submit';
    </script>

twido/templates/includes/login-required-row.html
            <div class="row">
                <div class="col-lg-3 col-lg-offset-3">
                    <div class="well bs-component">
                        <p>Forbidden.</p>
                        <p>You need to <a href="{% url 'login' %}">login</a> to view this page.</p>
                    </div>
                </div>
            </div>

twido/templates/includes/paginatition.html
{% if page.paginator.num_pages > 1 %}
    <!-- BEGIN pagination -->
    <ul class="pagination pagination-sm">

        <!-- page 1 -->
{#        {% if page.number > 1 %}#}
{#            <li><a href="?p=1">1</a></li>#}
{#        {% endif %}#}

        <!-- fast forward -->
        <li>
            <a href="?p={% if page.number|add:"-10" <= 0 %}1{% else %}{{ page.number | add:'-10' }}{% endif %}" aria-label="Prev">
            <span aria-hidden="true"><i class="glyphicon glyphicon-fast-backward"></i></span>
        </a></li>

        <!-- forward -->
        <li {% if not page.has_previous %}class="disabled"{% endif %}>
            <a href="{% if page.has_previous %}?p={{ page.previous_page_number }}{% endif %}" aria-label="Prev">
            <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-left"></i></span>
        </a></li>

{#        <li class="active btn"><a href="#">{{ page.number }}<span class="sr-only">(current)</span><i class="caret"></i></a></li>#}

        <!-- list all pages in dropdown -->
        <li class="btn-group dropup active">
            <!-- current page -->
            <a href="#">{{ page.number }}<span class="sr-only">(current)</span></a>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li class="container small" style="width:350px;">
                        <ul class="pagination pagination-sm">
                            {% for i in page.paginator.page_range %}
                                <li {% if page.number == i %}class="active"{% endif %}><a href="?p={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        </ul>
                </li>
            </ul>
        </li>

        <!-- backward -->
        <li {% if not page.has_next %}class="disabled"{% endif %}>
            <a href="{% if page.has_next %}?p={{ page.next_page_number }}{% endif %}" aria-label="Next">
                <span aria-hidden="true"><i class="glyphicon glyphicon-chevron-right"></i></span>
            </a>
        </li>

        <!-- fast backward -->
        <li>
            <a href="?p={% if page.number|add:"10" > page.paginator.num_pages %}{{ page.paginator.num_pages }}{% else %}{{ page.number|add:'10' }}{% endif %}" aria-label="Prev">
            <span aria-hidden="true"><i class="glyphicon glyphicon-fast-forward"></i></span>
        </a></li>

        <!-- last page -->
{#        {% if page.number < page.paginator.num_pages %}#}
{#            <li><a href="?p={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a></li>#}
{#        {% endif %}#}
    </ul>
    <!-- END pagination -->
{% endif %}

twido/templates/includes/profile-card-simple.html
<!-- BEGIN Profile Card Simple -->
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <ul class="list-inline">
                                <li class="pull-left">
                                    <img class="img-circle" src="{{ profile.get_img_url }}">
                                </li>
                                <li class="pull-right ">
{#                                    <h3 class="panel-title">{{ p.get_name | safe }}</h3>#}
                                    <span class="text-default">{{ profile.get_name }}</span><br>
{#                                    <span class="small" style="color:silver">{{ profile.location }}</span><br>#}
{#                                    <span class="small" style="color:silver">{{ profile.user.date_joined }}</span><br>#}
                                </li>
                                <li class="clearfix"></li>
                            </ul>

                        </div>
                        <div class="panel-body">
{#                            <img src="{{ profile.img_url }}">#}
                            <div class="small">
                                <span>{{ profile.get_date_joined }}</span><br>
{#                                <span>Email: {{ profile.get_email }}</span><br>#}
{#                                <span>{{ profile.lang }}</span><br>#}
                                <span>{{ profile.location | default_if_none:''}}</span><br>
{#                                <span>{{ profile.timezone }}</span><br>#}
{#                                <span>UTC offset: {{ profile.utc_offset }}</span><br>#}
                            </div>
                        </div>
                    </div>
<!-- END Profile Card Simple -->

twido/templates/includes/reminder.html
{% load i18n staticfiles customer_tags %}

    {% if expiring_tasks %}
                        <li id="id_reminder" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false"><i class="glyphicon glyphicon-calendar"></i> {% trans 'Expiring' %}<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">

                                {% for task in expiring_tasks %}
                                <li class="small"><a name="due" href="{% url 'task' task.id %}"><span data-name="title">{{ task.title }}</span> - <span data-name="due" data-value="{{ task.due|utc }}">{{ task.due }}</span></a></li>
                                {% endfor %}

                            </ul>
                        </li>

                        <script language="JavaScript">
                            var website_name = "{{ website.name }}";

                            function notify(title, message, url){
                                var n = new Notification(title + ' - ' + website_name, {
                                    tag: website_name,
                                    lang: "utf-8",
                                    icon: "{% static 'twido/img/favicon.ico' %}",
                                    body: message
                                });
                                n.onclick = function(){
                                    window.location = $(obj).attr('href');
                                };
                                n.onclose = function(){
                                    //TODO: do not notify again.
                                };
                                return n;
                            }

                            function allow_notification(){
                                Notification.requestPermission(function(status){
                                    console.log(status);
                                    if(Notification.permission !== status){
                                        Notification.permission = status;
                                    }

                                    if(status === "granted"){
                                        var n = new Notification("{% trans "Task Reminder" %} - " + website_name, {
                                            tag: website_name,
                                            icon: "{% static 'twido/img/favicon.ico' %}",
                                            body: "{% trans "Welcome! You will be notified when your task is going to be due." %}"
                                        });
                                    }
                                });
                            }

                            $(document).ready(function(){
                                {# visit chrome://settings/content/notifications to un-block #}

                                if (Notification.permission !== "granted") {
                                    $("#id_reminder").find("ul").append(
                                            '<li class="divider"></li>' +
                                            '<li class="small"><a class="btn" onclick="allow_notification()">' +
                                            '<i class="fa fa-bell"></i> {% trans "Allow task due notification in browser" %}' + '</a></li>');
                                }

                                $("#id_reminder").find("ul").find("li a[name='due']").each(function(idx, obj){
                                    var title = $(obj).find("span[data-name='title']").text();
                                    var due = $(obj).find("span[data-name='due']").data('value');
                                    var url = $(obj).attr('href');
                                    due = new Date(due);
                                    var duration = due - new Date();    // millisecond already
                                    duration -= 300000;  // alert before 5 min. //TODO: make it in setting.
                                    if (duration < 0)
                                        duration = 1000;
                                    setTimeout(function(){
                                        notify('{% trans 'Task is expiring' %}: ',
                                                title + '\n' + due.toLocaleString(),
                                                url);
                                    }, duration)
                                });
                            });
                        </script>

    {% endif %}