twido/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views


# to render full template path
def t(template):
    return 'twido/' + template

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # (r'^robots\.txt$', 'django.views.generic.simple.direct_to_template', {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    # (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

    url(r'^login/$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^register/$', views.RegisterView.as_view(template_name='registration/register.html'), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(template_name='registration/profile.html'), name='profile'),

    url(r'^$', views.IndexView.as_view(template_name=t('index.html')), name='index'),
    url(r'^home/$', views.HomeView.as_view(template_name=t('home.html')), name='home'),
    url(r'^setting/$', views.SettingView.as_view(template_name=t('setting.html')), name='setting'),

    url(r'^social/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>link)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>update)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>login)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),

    url(r'^list/$', views.ListView.as_view(template_name=t('list.html')), name='list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.ListView.as_view(template_name=t('list.html')), name='list'),

    url(r'^task/(?P<pk>[0-9]+)/$', views.TaskView.as_view(template_name=t('task.html')), name='task'),

    url(r'^json/usernames/$', views.ProfileUsernamesJsonView.as_view()),

    # url(r'^', include('user.urls')),

]

# debug & test
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.extend([
        url(r'^test/$', views.test, name='test'),
        url(r'^test/(?P<pk>[0-9]+)/$', views.test, name='test'),
        url(r'^debug/', include(debug_toolbar.urls)),
    ])

twido/models/admins.py
#!/usr/bin/env python
# coding: utf-8

"""
Model admin pages and forms
"""
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import AppRegistryNotReady
from django.db import transaction
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy
from .common import Config, UserProfile
from .social import SocialAccount
try:
    UserModel = get_user_model()
except AppRegistryNotReady:
    from django.contrib.auth.models import User as UserModel

import logging
log = logging.getLogger(__name__)


class I18N_MSGS(object):
    email_lable = _("Email")
    email_help = _("Enter the user email.")
    email_exists = _('A user with that email already exists.')
    email_required = _('Email is required.')


# ---- admins -----

class RawStatusAdmin(admin.ModelAdmin):
    list_display = ('id', 'rawid', 'source', 'created_at', 'username', 'text', 'timestamp')
    # exclude = ['raw']
    # fieldsets = (
    #     (None, {
    #         'fields': ('id', 'created_at', 'user', 'text',)
    #     }),
    #     ('Advanced options', {
    #         'classes': ('collapse',),
    #         'fields': ('raw', ),
    #     }),
    # )


# @admin.register(RawTweet)
# class RawTweetAdmin(RawStatusAdmin):
#     """
#     Admin page for RawTweet
#     """
#     pass


@admin.register(Config)
class ConfigAdmin(admin.ModelAdmin):
    """
    Admin page for configurations.
    """
    list_display = ('id', 'profile', 'name', 'value')
    list_display_links = ('id', 'name')


# @admin.register(UserProfile)
# class UserProfileAdmin(admin.ModelAdmin):
#     """
#     User profile admin page
#     """
#     pass


@admin.register(SocialAccount)
class SocialAccountAdmin(admin.ModelAdmin):
    """
    Admin page for configurations.
    """
    # list_display = ('__all__', )
    # list_display_links = ('id', 'name')
    pass


# ---- forms -----

class UserProfileCreationForm(UserCreationForm):
    """
    Django User is used for authorization (login/logout/register). User.username will always set to User.email.
    """
    email = forms.EmailField(
        label=I18N_MSGS.email_lable,
        widget=forms.EmailInput,
        strip=True,
        help_text=I18N_MSGS.email_help,
    )

    class Meta:
        model = UserModel
        fields = ("email", "username")
        field_classes = {'email': forms.EmailField, 'username': forms.CharField}

    def __init__(self, *args, **kwargs):
        super(UserProfileCreationForm, self).__init__(*args, **kwargs)
        if 'email' in self.fields:
            self.fields['email'].widget.attrs.update({'autofocus': ''})

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise forms.ValidationError(
                I18N_MSGS.email_required,
                code='email_required'
            )
        try:
            profile = UserProfile.objects.get(email=email)
            if profile and profile.user:
                raise forms.ValidationError(
                    I18N_MSGS.email_exists,
                    code='email_exists'
                )
        except UserProfile.DoesNotExist:
            pass
        return email

    def clean(self):
        cleaned_data = super(UserProfileCreationForm, self).clean()
        email = cleaned_data.get('email')
        username = cleaned_data.get('username')
        if not username:
            cleaned_data['username'] = email

        return cleaned_data

    def save(self, commit=True):
        """

        :param commit: whether save to DB. If False, will only create instance without save to DB.)
        :return: UserProfile instance (not User instance, use profile.user to access user instance)
        """
        user = super(UserProfileCreationForm, self).save(commit=False)
        # user.is_active = False  # need to verify email.
        email = self.cleaned_data['email']
        password = self.clean_password2()
        # assert user
        # if not user.username:
        #     user.username = email
        # assert user.username
        # profile = None
        # if commit:
        #     with transaction.atomic():
        #         user.save()
        #         assert user and user.username
        #         profile, created = UserProfile.objects.get_or_create(user=user)
        #         profile.email = email
        #         if created:
        #             log.warn('Profile was not created after User created. (%s)' % user.username)
        #             profile.name = user.email[:user.email.find('@')]
        #             profile.username = profile.name + str(int(timezone.now().timestamp()))
        #         profile.save()
        # return profile

        profile, passwd = UserProfile.register(email=email, password=password, commit=True)
        return profile

twido/models/common.py
#!/usr/bin/env python
# coding: utf-8

"""
Common models
"""
from django.contrib.auth import get_user_model
from django.core.exceptions import AppRegistryNotReady
from django.db import models
from django.db import transaction
from django.contrib.auth.hashers import make_password
from django.utils import timezone
from django.utils.translation import pgettext_lazy
from .consts import Gender

try:
    UserModel = get_user_model()
except AppRegistryNotReady:
    from django.contrib.auth.models import User as UserModel

import logging
log = logging.getLogger(__name__)


class UserProfile(models.Model):
    """
    User Profile.

    Django User is used for authorization (login/logout/register).
    User.username will always be set to User.email.
    The Django User.email field is useless.

    email -> login account.
    username -> user.username. Account ID.
    name -> display/nick name. user.first_name/last_name will be ignore
    """
    id = models.BigAutoField(primary_key=True)

    # TODO: null or not ? make __sys__ user locked ?
    # null means faked profile
    user = models.OneToOneField(to=UserModel, related_name='profile', db_index=True, null=True, blank=True)
    email = models.CharField(max_length=100, unique=True, db_index=True, editable=False)    # user.email
    username = models.CharField(max_length=100, unique=True, db_index=True, null=True)
    created_at = models.DateTimeField(editable=False)

    name = models.CharField(max_length=100, null=True, blank=True)  # real/nick/display name
    gender = models.CharField(max_length=1, default=Gender.PRIVATE, choices=Gender.Choices)
    timezone = models.CharField(max_length=50, null=True, blank=True)
    location = models.TextField(null=True, blank=True)
    lang = models.CharField(max_length=20, default='en', verbose_name='Language')
    utc_offset = models.IntegerField(verbose_name='UTC offset hours', default=0)
    img_url = models.URLField(verbose_name='Image URL', null=True, blank=True)
    timestamp = models.DateTimeField(auto_now=True)

    __sys_profile = None
    __sys_profile_uname = '__sys__'
    # __anonymous_profile = None
    # __anonymous_profile_uname = '__anonymous'

    __temp_profile_email_suffix = '@temp'
    __local_profile_email_suffix = '@local'

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super(UserProfile, self).save(*args, **kwargs)

    @classmethod
    def init_data(cls):
        p, created = cls.objects.get_or_create(username=cls.__sys_profile_uname)
        if created:
            p.email = cls.__sys_profile_uname + cls.__local_profile_email_suffix
            p.name = pgettext_lazy('system account name', 'SYS')
            p.save()
            log.info('System profile (%s) is created.' % cls.__sys_profile_uname)
        cls.__sys_profile = p

        # p, created = cls.objects.get_or_create(username=cls.__anonymous_profile_uname)
        # if created:
        #     p.email = cls.__anonymous_profile_uname + cls.__local_profile_email_suffix
        #     p.name = pgettext_lazy('anonymous account name', 'SYS')
        #     p.save()
        #     log.info('Anonymous profile (%s) is created.' % cls.__anonymous_profile_uname)
        # cls.__anonymous_profile = p

    @classmethod
    def get_sys_profile(cls):
        if cls.__sys_profile is None:
            cls.init_data()
        return cls.__sys_profile

    @classmethod
    def get_sys_profile_username(cls):
        return cls.__sys_profile_uname

    @property
    def is_sys(self):
        return self == self.get_sys_profile()

    # @classmethod
    # def get_anonymous_profile(cls):
    #     if cls.__anonymous_profile is None:
    #         cls.init_data()
    #     return cls.__anonymous_profile
    #
    # @classmethod
    # def get_anonymous_profile_username(cls):
    #     return cls.__anonymous_profile_uname

    @property
    def is_temp(self):
        return self.email.endswith(self.__temp_profile_email_suffix)

    @classmethod
    def register_temp(cls, username, platform='', commit=True, **kwargs):
        if not platform:
            platform = cls.__local_profile_email_suffix
        email = username + '.' + platform + cls.__temp_profile_email_suffix
        username = username + '.' + platform
        profile, password = cls.register(email=email, username=username, commit=commit, **kwargs)
        return profile, password

    @classmethod
    @transaction.atomic
    def register(cls, email, username='', password='', active=True, commit=True, **kwargs):

        name = email[:email.find('@')]
        if not username:
            username = name + str(int(timezone.now().timestamp()))
        if not password:
            password = UserModel.objects.make_random_password()
        user = UserModel(username=email, email=email, is_active=active)
        user.set_password(password)
        profile = UserProfile(email=email, username=username, name=name, **kwargs)
        if commit:
            with transaction.atomic():
                user.save()
                profile.user = user
                profile.save()
        return profile, password

    def get_email(self):
        return self.email

    def get_name(self):
        """
        Return a display name. (never return email or user.username)
        :return a display name
        """
        if self.name:
            return self.name
        elif self.username:
            return self.username
        elif self.is_faked:
            return self.id
        return self.user.id

    def get_date_joined(self):
        return self.created_at

    def get_img_url(self):
        if self.img_url:
            return self.img_url
        else:
            return Gender.get_img(self.gender)

    def get_gender_icon(self):
        return Gender.get_icon(self.gender)

    def get_gender_text(self):
        return Gender.get_text(self.gender)

    @property
    def is_faked(self):
        return self.user is None

    def __str__(self):
        return '%s (id=%d)' % (self.email, self.id)

    @classmethod
    def get_temp_email_suffix(cls):
        return cls.__temp_profile_email_suffix

    @classmethod
    def get_local_email_suffix(cls):
        return cls.__local_profile_email_suffix


class ProfileBasedModel(models.Model):
    """
    The base model for all models which need id, profile and timestamp.
    Basically all account related models should inherit this model.
    """
    id = models.BigAutoField(primary_key=True)
    profile = models.ForeignKey(to=UserProfile, db_index=True)
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def to_dict(self, fields=()):
        if fields:
            return type(self).objects.filter(id=self.id).values(fields)[0]
        else:
            return type(self).objects.filter(id=self.id).values()[0]

    def from_dict(self, thedict):
        for k, v in thedict.items():
            if hasattr(self, k):
                setattr(self, k, v)


class Config(ProfileBasedModel):
    """
    Common configurations name-value list.
    Represents system configurations if self.profile is None
    """
    name = models.CharField(max_length=100, db_index=True)
    value = models.TextField()

    class Meta:
        unique_together = ('profile', 'name')

    def __str__(self):
        return '%s=%s' % (self.name, self.value)

    @classmethod
    def get_user_conf(cls, profile, name):
        try:
            return cls.objects.get(profile=profile, name=name)
        except cls.DoesNotExist:
            return None

    @classmethod
    def get_or_create_user_conf(cls, profile, name):
        return cls.objects.get_or_create(profile=profile, name=name)

    @classmethod
    def set_user_conf(cls, profile, name, value):
        opt, created = cls.objects.get_or_create(profile=profile, name=name)
        opt.value = value
        opt.save()

    @classmethod
    def get_sys_conf(cls, name):
        try:
            return cls.objects.get(profile=UserProfile.get_sys_profile(), name=name)
        except cls.DoesNotExist:
            return None

    @classmethod
    def get_or_create_sys_conf(cls, name):
        return cls.objects.get_or_create(profile=UserProfile.get_sys_profile(), name=name)

    @classmethod
    def set_sys_conf(cls, name, value):
        opt, created = cls.objects.get_or_create(profile=UserProfile.get_sys_profile(), name=name)
        opt.value = value
        opt.save()

twido/forms.py
#!/usr/bin/env python
# coding: utf-8

from django.forms import ModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from django.db import transaction
import logging
from django.utils import timezone
log = logging.getLogger(__name__)

UserMode = get_user_model()



# class TodoListForm(ModelForm):
#     class Meta:
#         model = TodoList
#         fields = ['name', 'due', 'related_users', 'text']
#         widgets = {
#             'due': forms.SplitDateTimeWidget(),
#         }
#
#
# class TodoForm(forms.ModelForm):
#     class Meta:
#         model = Todo
#         fields = '__all__'

twido/views.py
#!/usr/bin/env python
# coding: utf-8

"""
views
"""

from django.conf import settings
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseBadRequest
from django.urls import reverse

import logging
log = logging.getLogger(__name__)


# to render full template path
def t(template):
    return 'twido/' + template


# test view for some test purpose
if __debug__ and settings.DEBUG:
    def test(request):
        return render(request, t('test.html'))


@require_http_methods(['GET', ])
def index(request):
    context = {}
    if request.user.is_authenticated:
        context['user'] = 'authoried'
    elif request.user.is_staff:
        context['user'] = 'staff'
    else:
        context['user'] = 'forbiden'
    # context = {
    #     # "setting_keys": models.SETTING_NAMES,
    # }
    return render(request, t('index.html'), context=context)

twido/templates/twido/includes-setting/_dropdown.sample.html
                            <div class="tab-pane fade" id="dropdown2">

                                <fieldset>
                                    <legend>{% trans "Profile" %}</legend>


                                    <div class="form-group {% if 'email' in errors %}has-error{% endif %}">
                                        <label for="id_email" class="col-lg-3 control-label">{% trans 'Email' %}</label>

                                        <div class="col-lg-9">
                                            <span class="form-control" id="id_email">{{ profile.email }}</span>
                                            <span class="help-block small">{% trans 'Account ID, unique in system. Immutable.' %}</span>
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'username' in errors %}has-error{% endif %}">
                                        <label for="id_username"
                                               class="col-lg-3 control-label">{% trans 'Username' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" autofocus="" id="id_username"
                                                   placeholder="User screen name"
                                                   maxlength="150" name="username" required="" type="text"
                                                   value="{{ profile.username }}">
                                            <span class="help-block small">{% trans 'Account/screen name, unique in system.' %}</span>

                                        </div>
                                    </div>
                                    <div class="form-group {% if 'name' in errors %}has-error{% endif %}">
                                        <label for="id_name" class="col-lg-3 control-label">{% trans 'Name' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" id="id_name" name="name"
                                                   placeholder="Real Name" type="text"
                                                   value="{{ profile.name|default_if_none:'' }}">
                                            <span class="help-block small">{% trans 'Real name or display name' %}</span>
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'gender' in errors %}has-error{% endif %}">
                                        <label for="id_gender"
                                               class="col-lg-3 control-label">{% trans 'Gender' %}</label>

                                        <div class="col-lg-9">
                                            <div class="radio">
                                                <label><img class="avatar-sm"
                                                            src="{% static 'twido/img/avatar-man.png' %}"> <input
                                                        name="gender" id="id_gender1" value="1"
                                                        {% if profile.gender %}checked=""{% endif %}
                                                        type="radio">
                                                    {% trans 'Male' %}
                                                </label> &nbsp;
                                                <label><img class="avatar-sm"
                                                            src="{% static 'twido/img/avatar-woman.png' %}"> <input
                                                        name="gender" id="id_gender2" value=""
                                                        {% if not profile.gender %}checked=""{% endif %} type="radio">
                                                    {% trans 'Female' %}
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'timezone' in errors %}has-error{% endif %}">
                                        <label for="id_timezone"
                                               class="col-lg-3 control-label">{% trans 'Timezone' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" id="id_timezone" name="timezone"
                                                   placeholder="Timezone" type="text"
                                                   value="{{ profile.timezone|default_if_none:'' }}">
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'location' in errors %}has-error{% endif %}">
                                        <label for="id_location"
                                               class="col-lg-3 control-label">{% trans 'Location' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" id="id_location" name="location"
                                                   placeholder="San Jose, US" type="text"
                                                   value="{{ profile.location|default_if_none:'' }}">
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'lang' in errors %}has-error{% endif %}">
                                        <label for="id_lang"
                                               class="col-lg-3 control-label">{% trans 'Language' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" id="id_lang" name="lang"
                                                   placeholder="Language" type="text"
                                                   value="{{ profile.lang|default_if_none:'en' }}">
                                        </div>
                                    </div>
                                    <div class="form-group {% if 'img_url' in errors %}has-error{% endif %}">
                                        <label for="id_img_url"
                                               class="col-lg-3 control-label">{% trans 'Image' %}</label>

                                        <div class="col-lg-9">
                                            <input class="form-control" id="id_img_url" name="img_url"
                                                   placeholder="Image" type="text"
                                                   value="{{ profile.img_url|default_if_none:'' }}">
                                        </div>
                                    </div>

                                </fieldset>

                            </div>

twido/templates/twido/includes-setting/general.html
{# Account Linking setting #}
{# vars: errors - field_name:error_message pair #}
{#       configs - the config dict #}
{% load i18n %}<!-- BEGIN general setting -->
                                <fieldset>
                                    <legend>{% trans "General" %}</legend>

                                    <div class="form-group {% if 'lang' in errors %}has-error{% endif %}">
                                        <label for="id_lang" class="col-lg-3 control-label">{% trans 'Language' %}</label>

                                        <div class="col-lg-9">
{#                                            <input class="form-control editable" id="id_lang" name="lang" data-name="lang" data-type="select"  value="{{ conf.lang }}">#}
                                            <span class="form-control editable" id="id_lang" data-type="select" data-name="lang" data-pk="{{ conf.lang.id }}" ></span>
                                            <span class="help-block small">{% trans 'Preferred UI display language and formats.' %}</span>
                                        </div>
                                    </div>

                                    <div class="form-group {% if 'theme' in errors %}has-error{% endif %}">
                                        <label for="id_theme" class="col-lg-3 control-label">{% trans 'Theme' %}</label>

                                        <div class="col-lg-9">
                                            <span class="form-control editable" id="id_theme" data-type="select" data-name="theme" data-pk="{{ conf.theme.id }}" ></span>
                                            <span class="help-block small">{% trans 'Theme to render the site.' %}</span>
                                        </div>
                                    </div>

{#                                    <div class="form-group {% if 'view_size' in errors %}has-error{% endif %}">#}
{#                                        <label for="id_view_size" class="col-lg-3 control-label">{% trans 'Font Size' %}</label>#}
{##}
{#                                        <div class="col-lg-9">#}
{#                                            <span class="form-control editable" id="id_view_size" data-type="select" data-name="view_size" data-pk="{{ conf.view_size.id }}" ></span>#}
{#                                            <span class="help-block small">{% trans 'Size to view the site.' %}</span>#}
{#                                        </div>#}
{#                                    </div>#}

                                </fieldset>
                                <script language="JavaScript" type="text/javascript">
{#                                    {% get_current_language as LANGUAGE_CODE %}#}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    $(document).ready(function(){
                                        var languages = [
                                                {% for language in languages %}
                                                {value: "{{ language.code }}", text: "{{ language.name_local }} ({{ language.code }})"},
                                                {% endfor %}
                                            ];
                                        $('#id_lang').editable({
                                            url: "{% url 'setting' %}",
                                            value: "{{ conf.lang.value }}",
                                            source: languages,
                                            success: function (response, newValue) {
                                                if (response.status == "error") {
                                                    return response.msg;
                                                } else {
{#                                                    location.reload();#}
                                                }
                                            }
                                        });

                                        var themes = [
                                            {% for theme in themes %}
                                            {value: "{{ theme.0 }}", text: "{{ theme.1 }}"},
                                            {% endfor %}
                                        ];
                                        $('#id_theme').editable({
                                            url: "{% url 'setting' %}",
                                            value: "{{ conf.theme.value }}",
                                            source: themes,
                                            success: function (response, newValue) {
                                                if (response.status == "error") {
                                                    return response.msg;
                                                } else {
                                                    location.reload();
                                                }
                                            }
                                        });

{#                                        var view_sizes = [#}
{#                                            {value: 'G', text: "{% trans 'general'|capfirst %}"},#}
{#                                            {value: 'S', text: "{% trans 'small'|capfirst %}"},#}
{#                                            {value: 'L', text: "{% trans 'large'|capfirst %}"},#}
{#                                        ];#}
{#                                        $('#id_view_size').editable({#}
{#                                            url: "{% url 'setting' %}",#}
{#                                            value: "{{ conf.view_size.value|default:'G' }}",#}
{#                                            source: view_sizes,#}
{#                                            success: function (response, newValue) {#}
{#                                                if (response.status == "error") {#}
{#                                                    return response.msg;#}
{#                                                } else {#}
{#                                                    location.reload();#}
{#                                                }#}
{#                                            }#}
{#                                        })#}
                                    });

                                </script>
<!-- END general setting -->