twido/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from . import views


# to render full template path
def t(template):
    return 'twido/' + template

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # (r'^robots\.txt$', 'django.views.generic.simple.direct_to_template', {'template': 'robots.txt', 'mimetype': 'text/plain'}),
    # (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),

    url(r'^login/$', views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^register/$', views.RegisterView.as_view(template_name='registration/register.html'), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(template_name='registration/profile.html'), name='profile'),

    url(r'^$', views.IndexView.as_view(template_name=t('index.html')), name='index'),
    url(r'^home/$', views.HomeView.as_view(template_name=t('home.html')), name='home'),
    url(r'^setting/$', views.SettingView.as_view(template_name=t('setting.html')), name='setting'),

    url(r'^social/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>link)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>update)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),
    url(r'^social/(?P<action>login)/$', views.SocialView.as_view(template_name=t('social.html')), name='social'),

    url(r'^list/$', views.ListView.as_view(template_name=t('list.html')), name='list'),
    url(r'^list/(?P<pk>[0-9]+)/$', views.ListView.as_view(template_name=t('list.html')), name='list'),

    url(r'^task/(?P<pk>[0-9]+)/$', views.TaskView.as_view(template_name=t('task.html')), name='task'),

    url(r'^json/usernames/$', views.ProfileUsernamesJsonView.as_view()),

    # url(r'^', include('user.urls')),

]

# debug & test
if settings.DEBUG:
    import debug_toolbar
    urlpatterns.extend([
        url(r'^test/$', views.test, name='test'),
        url(r'^test/(?P<pk>[0-9]+)/$', views.test, name='test'),
        url(r'^debug/', include(debug_toolbar.urls)),
    ])

twido/models/task.py
#!/usr/bin/env python
# coding: utf-8

"""
Task and list related models
"""
from datetime import timedelta
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.core.validators import validate_comma_separated_integer_list
from django.utils.functional import SimpleLazyObject
from django.utils.translation import ugettext_lazy as _, pgettext_lazy, ugettext_noop
from django.db import transaction
from .common import ProfileBasedModel, UserProfile
from .consts import TaskStatus, Visibility
from pyutils.langutil import PropertyDict
from .social import SocialAccount
from .spider import RawStatus

import simplejson as json
import logging
from twido.parser import Timex3Parser

log = logging.getLogger(__name__)


class List(ProfileBasedModel):
    """
     A list contains one or more things you want or want to do. (todolist, wishlist, ...)
    """
    name = models.CharField(max_length=100)
    reminder = models.DateTimeField(null=True, blank=True)
    visibility = models.IntegerField(choices=Visibility.Choices, default=Visibility.PUBLIC, db_index=True)
    related_users = models.TextField(validators=[validate_comma_separated_integer_list], null=True, blank=True,
                                     db_index=True, verbose_name='Related Persons (comma separated)')
    text = models.TextField(null=True, blank=True)

    # class Meta:
    #     unique_together = ('profile', 'name')

    __default_name = '__default__'

    def __str__(self):
        return "%s (id=%d)" % (self.name, self.id)

    @classmethod
    def get_default(cls, profile):
        try:
            default_list = cls.objects.get(name=cls.__default_name, profile=profile)
        except cls.DoesNotExist:
            default_list = cls(name=cls.__default_name, profile=profile)
            default_list.text = ugettext_noop('The default list contains unlisted tasks.')
            default_list.save(is_default=True)
        return default_list

    @property
    def is_default(self):
        return self.name == self.__default_name

    @property
    def is_sys(self):
        return self.name.startswith('__')

    @property
    def default(self):
        return self.get_default(self.profile)

    def get_name(self):

        if self.is_default:
            return pgettext_lazy('sys list', 'default')
        elif self.is_sys:
            return pgettext_lazy('sys list', self.name.lstrip('_'))
        else:
            return self.name

    def get_related_profiles(self):
        return UserProfile.objects.filter(username__in=(self.related_users.split(',') or ''))

    def get_related_usernames(self):
        return self.related_users.split(',')

    def get_visibility_text(self):
        return Visibility.get_text(self.visibility)

    def get_visibility_icon(self):
        return Visibility.get_icon(self.visibility)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None, is_default=False):
        if not is_default and self.name.lower() == self.__default_name:
            raise AttributeError('List name can not be "%s" (reversed default name). ' % self.name)
        return super(List, self).save(force_insert=force_insert, force_update=force_update,
                                      using=using, update_fields=update_fields)

    def delete(self, using=None, keep_parents=False):
        s = str(self)
        log.debug('deleting list %s' % s)
        with transaction.atomic():
            # This query ref to Task. So to avoid recursive reference, need to put List in same file with Task
            Task.objects.filter(list=self, profile=self.profile).update(list=self.get_default(self.profile))
            log.debug('all tasks in todo list %s are moved to default list.' % s)
            super(List, self).delete(using=using, keep_parents=keep_parents)
            log.info('todo list %s is deleted.' % s)


class Task(ProfileBasedModel):
    """
    Base task model for todo, wish and schedule appointment
    """
    created_at = models.DateTimeField(editable=False)
    title = models.CharField(max_length=100)
    status = models.IntegerField(choices=TaskStatus.Choices, default=TaskStatus.NEW, db_index=True)
    visibility = models.IntegerField(choices=Visibility.Choices, default=Visibility.PUBLIC, db_index=True)
    text = models.TextField(null=True, blank=True)
    labels = models.TextField(null=True, blank=True)
    due = models.DateTimeField(null=True, blank=True, db_index=True)
    list = models.ForeignKey(to=List)
    social_account = models.ForeignKey(to=SocialAccount, db_index=True, null=True, blank=True)

    content = models.TextField(null=True, blank=True)
    raw = models.OneToOneField(to=RawStatus, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()
        super(Task, self).save(*args, **kwargs)

    def get_owner_name(self):
        if self.profile and not self.profile.is_sys:
            return self.profile.get_name()
        elif self.social_account:
            return self.social_account.name or self.social_account.account

    def get_at_name(self):

        if self.profile.is_faked:
            uname = self.social_account.account
        else:
            uname = self.profile.username
        return '@' + uname

    def get_status_text(self):
        return TaskStatus.get_text(self.status)

    def get_status_icon(self):
        return TaskStatus.get_icon(self.status)

    def get_visibility_text(self):
        return Visibility.get_text(self.visibility)

    def get_visibility_icon(self):
        return Visibility.get_icon(self.visibility)

    def get_view_path(self):
        return reverse('task', args=(self.id, ))

    def __str__(self):
        return '%s (id=%d)' % (self.title, self.id)


class TaskMeta(models.Model):
    task = models.OneToOneField(to=Task, related_name='meta')
    timex = models.TextField(null=True, blank=True)
    dates = models.TextField(null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    persons = models.TextField(null=True, blank=True)
    simple_text = models.TextField(null=True, blank=True)

    _tags = []
    _dates = []

    def highlight_timex(self):
        return Timex3Parser.highlight(self.timex)

    def get_dates(self):
        if not self._dates:
            self._dates = json.loads(self.dates)
        return self._dates

    def get_tags(self):
        if not self._tags:
            self._tags = json.loads(self.tags)
        return self._tags

    def save(self, *args, **kwargs):
        super(TaskMeta, self).save(*args, **kwargs)
        self._tags = []
        self._dates = []


class SysList(object):
    """
    System pre-defined query list
    """

    soon_days = 3

    def __init__(self, profile, list_model=List, task_model=Task, entries_per_page=10):
        self.ListModel = list_model
        self.TaskModel = task_model
        self.profile = profile
        self.entries = entries_per_page
        self._meta = PropertyDict((
            ('__today', PropertyDict(
                name='__today',
                title=pgettext_lazy('sys list', 'today'),   # for i18n text generation usage
                text=ugettext_noop('Tasks need to be done by today. (including expired)'),
                tasks=SimpleLazyObject(self.__get_today_tasks)
            )),
            ('__coming', PropertyDict(
                name='__coming',
                title=pgettext_lazy('sys list', 'coming'),    # for i18n text generation usage
                text=ugettext_noop('Tasks in near future'),
                tasks=SimpleLazyObject(self.__get_coming_tasks)
            )),
            ('__expired', PropertyDict(
                name='__expired',
                title=pgettext_lazy('sys list', 'expired'),   # for i18n text generation usage
                text=ugettext_noop('Tasks passed the deadline.'),
                tasks=SimpleLazyObject(self.__get_expired_tasks)
            )),
            ('__all', PropertyDict(
                name='__all',
                title=pgettext_lazy('sys list', 'all'),   # for i18n text generation usage
                text=ugettext_noop('All my tasks.'),
                tasks=SimpleLazyObject(self.__get_all_tasks)
            )),
        ))

        # for translation usage (not working)
        # for meta in self._meta.values():
        #     meta.title = pgettext_lazy('sys list', meta.name.lstrip('_'))

        self._lists = PropertyDict()

    @property
    def all(self):
        if not self._lists:
            for name in self._meta.keys():
                self.get(name)
        return self._lists

    def __getitem__(self, item):
        return self.get(item)

    def get(self, name):
        if name not in self._lists:
            meta = self._meta[name]
            lst, created = self.ListModel.objects.get_or_create(profile=self.profile, name=name)
            if created:
                lst.text = meta.text
                lst.visibility = False
                lst.save()
                log.debug('list "%s" created.' % lst)
            lst.tasks = meta.tasks
            self._lists[name] = lst
        return self._lists[name]

    def __get_today_tasks(self):
        now = timezone.now()
        today = timezone.datetime(now.year, now.month, now.day, tzinfo=timezone.utc)
        tomorrow = today + timedelta(days=1)
        return self.TaskModel.objects.filter(profile=self.profile, due__range=(today, tomorrow))

    def __get_coming_tasks(self):
        now = timezone.now()
        soon = now + timedelta(days=self.soon_days)
        return self.TaskModel.objects.filter(profile=self.profile).filter(
            Q(due__gt=now) & Q(due__lt=soon) | Q(due=None))

    def __get_expired_tasks(self):
        return self.TaskModel.objects.filter(profile=self.profile, due__lt=timezone.now()).exclude(

twido/views.py
#!/usr/bin/env python
# coding: utf-8

"""
views
"""

from django.conf import settings
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.shortcuts import redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse, HttpResponseNotFound, HttpResponseBadRequest
from django.urls import reverse

import logging
log = logging.getLogger(__name__)


# to render full template path
def t(template):
    return 'twido/' + template


# test view for some test purpose
if __debug__ and settings.DEBUG:
    def test(request):
        return render(request, t('test.html'))


@require_http_methods(['GET', ])
def index(request):
    context = {}
    if request.user.is_authenticated:
        context['user'] = 'authoried'
    elif request.user.is_staff:
        context['user'] = 'staff'
    else:
        context['user'] = 'forbiden'
    # context = {
    #     # "setting_keys": models.SETTING_NAMES,
    # }
    return render(request, t('index.html'), context=context)

twido/views/account.py
#!/usr/bin/env python
# coding: utf-8
from django.contrib.auth import login
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.http import require_http_methods
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.views import login as login_func_view

from .base import BaseViewMixin
from ..models import UserProfileCreationForm
from ..models import SocialPlatform

import logging
log = logging.getLogger(__name__)


class I18N_MSGS(object):
    reg_success = _('Registration succeed.')
    redirect_to_profile = _('Redirect to profile updating page ... <br>'
                            'If redirection did not start, please <a href="%s">click me to profile</a>.')


@method_decorator(require_http_methods(['POST', 'GET']), name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
@method_decorator(never_cache, name='dispatch')
@method_decorator(sensitive_post_parameters(), name='dispatch')
class RegisterView(TemplateView, BaseViewMixin):
    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        success = False
        profile = None
        request = self.request

        if request.method == "POST":
            form = UserProfileCreationForm(data=self.request.POST)
            if form.is_valid():
                profile = form.save()
                success = True
            else:
                if 'username' in form.errors:
                    del form.errors['username']
        else:
            form = UserProfileCreationForm()

        context['form'] = form
        context['success'] = success

        if success and profile and profile.user and profile.user.is_active:
            login(request, profile.user)
            self.success(I18N_MSGS.reg_success)
            self.success(I18N_MSGS.redirect_to_profile % reverse('profile'))

        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


@method_decorator(require_http_methods(['POST', 'GET']), name='dispatch')
@method_decorator(csrf_protect, name='dispatch')
@method_decorator(never_cache, name='dispatch')
@method_decorator(sensitive_post_parameters(), name='dispatch')
class LoginView(TemplateView, BaseViewMixin):

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        if 'social_platforms' not in context:
            context['social_platforms'] = SocialPlatform
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return self.login(request, template_name=self.template_name, extra_context=context, **kwargs)

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        return self.login(request, template_name=self.template_name, extra_context=context, **kwargs)

    def login(self, request, template_name='registration/login.html',
              # redirect_field_name=REDIRECT_FIELD_NAME,
              # authentication_form=AuthenticationForm,
              extra_context=None, redirect_authenticated_user=False):
        return login_func_view(request, template_name=template_name,
                               # redirect_field_name=redirect_field_name,
                               # authentication_form=authentication_form,
                               extra_context=extra_context,
                               redirect_authenticated_user=redirect_authenticated_user)

twido/templates/twido/includes-list/list-buttons.html
{# List action buttons #}
{# vars: thelist - (optional) current list to display #}

{% load i18n %}<!-- BEGIN list buttons -->


                <!-- buttons for list -->
                <div class="bs-component">
                    <form id="id_form_list_action" action="{% if thelist %}{% url 'list' thelist.id %}{% else %}{% url 'list' %}{% endif %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action">
                        <div class="btn-group btn-group-justified btn-group-sm">
                            <a name="add" title="{% trans 'Create a new list' %}" class="btn btn-default btn-block"><i class="glyphicon glyphicon-list"></i> {% trans 'Create List' %}</a>
                            {% if thelist and not thelist.is_sys %}
                            <a name="del" title="{% trans 'Delete current list' %}" data-toggle="confirmation" class="btn btn-default btn-block"><i class="glyphicon glyphicon-remove"></i> {% trans 'Delete List' %}</a>
                            {% endif %}
                        </div>
                        <div class="btn-group btn-group-justified btn-group-sm">
                            {% if thelist %}
                            <a name="export" title="{% trans 'Export current list' %}" class="btn btn-default btn-block"><i class="glyphicon glyphicon-export"></i> {% trans 'Export List' %}</a>
                            {% endif %}
                            <a name="import" title="{% trans 'Import a list from file which was exported' %}" class="btn btn-default btn-block"><i class="glyphicon glyphicon-export"></i> {% trans 'Import List' %}</a>
                        </div>
                    </form>
                </div>

                <!-- upload form for import -->
                <form id="id_form_upload" method="post" action="{% url 'list' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {#  TODO: handle big file / streaming #}
                    <input type="hidden" name="action" value="import">
                    <input type="file" id="id_file_upload" name="choose_file" onchange="$(this).closest('form').submit();" style="display: none" />
                </form>

                <script language="JavaScript" type="text/javascript">

                    $(document).ready(function(){

                        var form_list_actions = $("#id_form_list_action");

                        form_list_actions.find("a.btn").tooltip({container: 'body'}).click(function(e){
                            var action = $(this).attr('name');
                            if (!action) return;
                            form_list_actions.find("input[name='action']").val(action);
                            // if action is "del" related, need to confirm
                            // if upload, need to let user to choose file.
                            if ($.inArray(action, ['del', 'del-task', 'import']) < 0) form_list_actions.submit();
                {#            $(this).disable();#}
                        });

                        form_list_actions.find('a[name="del"]').confirmation({
                            onConfirm: function () {
                                form_list_actions.submit();
                            },
                            html: 'true',
                            title: '<span class="text-danger">{% trans 'DANGER : Delete list' %} "{{ thelist.name }}(id:{{ thelist.id }})" ?</span>'
                                        +'<p/><p class="small">{% trans 'All tasks in this list will be moved to default list' %}',
                            placement: 'right'
                        });

                        form_list_actions.find('a[name="import"]').click(function(e){
                            var choose_file = $('input[name="choose_file"]');
                            choose_file.click();
                        });

                    });

                </script>
<!-- END list buttons -->

twido/templates/twido/includes-list/lists-menu.html
{# TodoList menu #}
{# vars: thelist - current list to display #}
{#       lists - query of all lists #}
{#       sys_lists - all system smart list. (use SysList to access) #}

{% load i18n %}<!-- BEGIN lists menu -->

                    <div class="btn-group-sm" name="sys_lists_incl">
                        {% for lst in sys_lists.values %}
                            <a href="{% url 'list' lst.id %}" data-id="{{ lst.id }}" data-name="{{ lst.name }}"
                               class="btn {% if thelist.id == lst.id %}active{% endif %}">
                                <i class="glyphicon {% if thelist.id == lst.id %}glyphicon-search{% else %}glyphicon-search{% endif %} small"> </i>
                                  {% trans lst.get_name %}
{#                                <span class="badge">{{ lst.tasks.count }}</span>#}
                            </a>
                        {% endfor %}
                    </div>

                    <div class="list-group" name="lists_incl"  style="overflow-y: auto; max-height: 400px; ">
                        <a href="{% url 'list' %}" data-id="{{ thelist.default.id }}" data-name="{{ thelist.default.name }}"
                           class="list-group-item {% if thelist.is_default %}active{% endif %}">
                            <h4 class="list-group-item-heading">{% trans 'Lists' %}</h4>
                        </a>
                        {% for lst in lists %}
                            {% if not lst.is_sys %}
                            <a href="{% url 'list' lst.id %}" data-id="{{ lst.id }}" data-name="{{ lst.name }}"
                               class="list-group-item dropable {% if thelist.id == lst.id %}active{% endif %}">
                                <i class="glyphicon {% if thelist.id == lst.id %}glyphicon-list-alt{% else %}glyphicon-list{% endif %} small"> </i>
                                  {{ lst.get_name }}
                                <span class="badge">{{ lst.task_set.count }}</span></a>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <script language="JavaScript" type="text/javascript">
                        $(document).ready(function(){
                            var list_menu = $('[name="lists_incl"]');
                            scroll_to_item(list_menu, list_menu.find(".list-group-item.active"));
                        });
                    </script>
<!-- END lists menu -->

twido/templates/twido/includes-list/task-buttons.html
{# Task action buttons #}
{# vars: thelist - (optional) current list to display #}

{% load i18n %}
<!-- BEGIN  Task buttons -->

                        <!-- buttons for task -->
                        <form id="id_form_task_action" action="{% if thelist %}{% url 'list' thelist.id %}{% else %}{% url 'list' %}{% endif %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action">
                            <div class="btn-group btn-group-justified btn-group-sm">
                                {% if not thelist.is_sys or thelist.is_default %}
                                <a name="add-task" title="{% trans 'Add a task to current list' %}" class="btn btn-info btn-block"><i class="glyphicon glyphicon-plus"></i> {% trans 'Create Task' %}</a>
                                {% endif %}
                                {% if thetask %}
                                <a name="del-task" title="{% trans 'Delete current task' %}" class="btn btn-info btn-block"><i class="glyphicon glyphicon-remove"></i> {% trans 'Delete Task' %}</a>
                                {% endif %}
                            </div>
                        </form>

                        <script language="JavaScript" type="text/javascript">
                            $(document).ready(function() {

                                var form_task_actions = $("#id_form_task_action");

                                form_task_actions.find("a.btn").tooltip({container: 'body'}).click(function (e) {
                                    var action = $(this).attr('name');
                                    if (!action) return;
                                    form_task_actions.find("input[name='action']").val(action);
                                    // if action is "del" related, need to confirm
                                    // if upload, need to let user to choose file.
                                    if ($.inArray(action, ['del', 'del-task', 'import']) < 0) form_task_actions.submit();
                                    {#            $(this).disable();#}
                                });
                                form_task_actions.find("a[name='del-task']").confirmation({
{#                                    onShow: function(e, obj) {#}
{#                                        $(obj).closest('ul').unbind('mouseout');#}
{#                                    },#}
{#                                    onHide: function(e, obj) {#}
{#                                        $(obj).closest('ul').bind('mouseout', function (e) {#}
{#                                            $(this).find(".buttons").hide();#}
{#                                        });#}
{#                                    },#}
                                    onConfirm: function (e, obj) {
                                        del_selected_task(obj.data('task-id'));
                                    },
                                    html: 'true',
                                    title: '<span class="text-danger">{% trans 'DANGER : Delete this task' %} ?</span>',
                                    placement: 'bottom'
                                });
                            });


                            function del_selected_task(task_id) {
                                var entry = $("[name='tasks_incl']").find(".active");
                                var task_name = entry.find("[data-name='title']").text();

                                if (entry.length == 0) {
                                    _error('{% trans "No task selected. please select one to delete." %}');
                                    return;
                                }

                                $.ajax("{{ request.path }}", {
                                    method: 'POST',
                                    data: {
                                        action: "del-task",
                                        task_id: task_id
                                    },
                                    success: function (resp) {
                                        _success('{% trans 'Task "{0}" deleted.' %}'.f(task_name), true);  // message incl
                                        console.debug('Task "' + task_name + '" (id=' + task_id + ') deleted.');
                                        entry.fadeOut();
                                    },
                                    error: function (resp) {
                                        if (resp.readyState == 0)
                                            _error('{% trans "Connection error." %}');
                                        else
                                            _error('{% trans 'Fail to delete task "{0}". <br>Status: {1} <br>Content: {2}' %}'.f(
                                                            task_name, resp.status, resp.statusText),
                                                    true);    // message incl
                                        entry.fadeOut().fadeIn().fadeOut().fadeIn();
                                        return resp.status + ' ' + resp.statusText;
                                    }
                                });
                            }
                        </script>
<!-- END  Task buttons -->